swagger: '2.0'

info:
  version: '0.1'
  title: CitySDK Issue reporting API
  description: The Issue reporting API for service requests to city's feedback system. Based on Open311 Georeport V2.
  termsOfService: (depends on server instance, for example Helsinki http://dev.hel.fi/issuereporting/tos)

host: asiointi.hel.fi
basePath: /palautews/rest/v1
schemes:
  - http
  - https
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
  - application/xml

parameters:
  responseFormat:
    name: response_format
    in: path
    description: Response format, can be either xml or json
    required: true
    type: string
    enum:
      - json
      - xml
  localeParam:
    name: locale
    description: Preferred language
    in: query
    required: false
    allowEmptyValue: false
    type: string

definitions:
  request_georeport:
    description: Service request (or generally feedback), standard GeoReport v2
    required:
    - service_request_id
    - status
    - service_code
    - requested_datetime
    properties:
      service_request_id:
        type: string
        description: Unique ID of the service request created.
      status:
        type: string
        enum:
          - open
          - closed
        description: Current status of the service request.
      status_notes:
        type: string
        description: Explanation of why status was changed to current state or more details on current status than conveyed with status alone.
      service_name: #todo Generalization and linking
        type: string
        description: The human readable name of the service request type.
      service_code:
        type: string
        format: uid
        description: The unique identifier for the service request type
      description:
        type: string
        description: A full description of the request or report submitted.
      agency_responsible:
        type: string
        description: Agency responsible for fulfilling or otherwise addressing the service request.
      service_notice:
        type: string
        description: Information about the action expected to fulfill the request or otherwise address the information reported.
      requested_datetime:
        type: string
        format: date-time
        description: Date and time when the service request was made.
      updated_datetime:
        type: string
        format: date-time
        description: Date and time when the service request was last modified. For requests with status=closed, this will be the date the request was closed.
      expected_datetime:
        type: string
        format: date-time
        description: The date and time when the service request can be expected to be fulfilled. This may be based on a service-specific service level agreement.
      address:
        type: string
        description: Human readable address or description of location. This should be provided from most specific to most general geographic unit, eg address number or cross streets, street name, neighborhood/district, city/town/village, county, postal code.
      address_id:
        #<?> optional or required?
        type: string
        description: Internal address ID used by a jurisdictions master address repository or other addressing system.
      zipcode:
        #<?> Already mentioned in address descr?
        type: string
        description: postal code for the location of the service request. (Redundant and field might be removed as it should be part of adress string)
      lat: #Generalisation with
        type: number
        format: double
        description: latitude using the (WGS84) projection.
      long:
        type: number
        format: double
        description: longitude using the (WGS84) projection.
      media_url:
        type: string
        format: uri
        #<?> so we write we don't know how to submit
        description: URL to media associated with the request, eg an image. A convention for parsing media from this URL has yet to be established, so currently it will be done on a case by case basis much like Twitter.com does. For example, if a jurisdiction accepts photos submitted via Twitpic.com, then clients can parse the page at the Twitpic URL for the image given the conventions of Twitpic.com. This could also be a URL to a media RSS feed where the clients can parse for media in a more structured way.

  request_citysdk:
    description: CitySDK extensions to service request in GeoReport v2
    required:
    - title
    properties:
      title:
        type: string
        description: Title description of service request
      media_urls:
        type: array
        description: Array of URLs pointing to images attached to the request
        items:
          type: string
      service_object_id:
        type: string
        description: Search or post service requests assigned to certain service objects, e.g trash bin
      service_object_type:
        type: string
        description: Type of the service object included in the service_object_id

  request_helsinki:
    description: Helsinki extensions to service request in CitySDK
    properties:
      tasks:
        type: array
        description: History of subtasks for this request
        items:
          #<?> define array here
          type: string

paths:
  /services.{response_format}:
    get:
      summary: Get a list of services and their descriptions
      responses:
        200:
          description: List of services
        400:
          description: The URL request is invalid or service is not running or reachable. Client should notify us after checking URL
    parameters:
    - $ref: '#/parameters/responseFormat'
    - $ref: '#/parameters/localeParam'

  /services/{service_code}.{response_format}:
    get: 
      summary: Query service definition
      responses:
        200:
          description: Definition for a service
        400:
          description: The URL request is invalid or service is not running or reachable. Client should notify us after checking URL
    parameters:
    - name: service_code
      in: path
      description: The unique identifier for the service request type.
      required: true
      type: string
    - $ref: '#/parameters/responseFormat'
    - $ref: '#/parameters/localeParam'

  /requests.{response_format}:
    get:
      summary: Query list of service requests
      responses:
        200:
          description: List of service requests
        400:    
          description: The URL request is invalid or service is not running or reachable. Client should notify us after checking URL
      parameters:
      - $ref: '#/parameters/responseFormat'
      - $ref: '#/parameters/localeParam'  
      - name: service_request_id
        in: query
        description: Unique service request id
        required: false
        type: string
      - name: start_time
        in: query
        description: Query service requests after start time
        required: false
        type: string
        format: date
      - name: end_time
        in: query
        description: Query service requests before the end time
        required: false
        type: string
        format: date
      - name: updated_after
        in: query
        description: Earliest updated_datetime to include in search.
        required: false
        type: string
        format: date
      - name: updated_before
        in: query
        description: Latest updated_datetime to include in search.
        required: false
        type: string
        format: date
      - name: radius
        in: query
        description: Search service requests within radius from the lat, long center
        required: false
        type: string
      - name: service_code
        in: query
        description: Comma separated list of service_code values to search for
        required: false
        type: array
        items:
          type: integer
      - name: lat
        in: query
        description: Latitude of the issue to be searched for or posted
        required: false
        type: string
        default: '50'
      - name: long
        in: query
        description: Longitude of the issue to be searched for or posted
        required: false
        type: string
      - name: service_object_id
        in: query
        description: Search or post service requests assigned to certain service objects, e.g trash bin
        required: false
        type: string
      - name: service_object_type
        in: query
        description: Type of the service object included in the service_object_id
        required: false
        type: string
      - name: extensions
        in: query
        description: True if city specific extensions are requested. Default value is false.
        required: false
        type: string
        default: 'false'

    post:
      summary: Posting service requests
      responses:
        200:
          description: Request has been accepted
        400:
          description: The URL request is invalid or service is not running or reachable. Client should notify us after checking URL
        403:
          description: Missing or Invalid API Key
      parameters:
      - name: api_key
        in: formData
        description: API key
        required: true
        type: string
      - name: service_code
        in: formData
        description: Service code for the issue, as returned by /services
        required: true
        type: string
      - name: description
        in: formData
        description: Description of the service request
        required: true
        type: string
      - name: title
        in: formData
        description: Title description of service request
        required: false
        type: string
      - name: media_url
        in: formData
        description: Link to media source such as image
        required: false
        type: string
      - name: 'media[]'
        in: formData
        description: Media file
        required: false
        type: file
      - name: email
        in: formData
        description: Email
        required: false
        type: string
      - name: first_name
        in: formData
        description: First name
        required: false
        type: string
      - name: last_name
        in: formData
        description: Last name
        required: false
        type: string
      - name: address_string
        in: formData
        description: Address of the service request
        required: false
        type: string
      - name: phone
        in: formData
        description: Phone number
        required: false
        type: string
      - name: lat
        in: formData
        description: Latitude of the issue to be searched for or posted
        required: false
        type: string
      - name: long
        in: formData
        description: Longitude of the issue to be searched for or posted
        required: false
        type: string
      - name: service_object_id
        in: formData
        description: Search or post service requests assigned to certain service objects, e.g trash bin
        required: false
        type: string
      - name: service_object_type
        in: formData
        description: Type of the service object included in the service_object_id
        required: false
        type: string

    parameters:
    - $ref: '#/parameters/responseFormat'

  /requests/{service_request_id}.{response_format}:
    get:
      summary: Query individual service requests
      responses:
        200:
          description: Information for the request
        400:
          description: The URL request is invalid or service is not running or reachable. Client should notify us after checking URL
    parameters:
    - $ref: '#/parameters/responseFormat'
    - name: service_request_id
      in: path
      description: Unique service request id
      required: true
      type: string
    - name: extensions
      in: query
      description: True if city specific extensions are requested. Default value is false.
      required: false
      type: string
      default: 'false'
